//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsAgenda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int Id_Contacto { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Direcion { get; set; }
        public string Usuario { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
